version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Botfile
    container_name: wasd_bot
    environment:
      BOT_TOKEN: ${TOKEN}
    depends_on:
      - db
    restart: always

  poller:
    build:
      context: .
      dockerfile: Pollerfile
    container_name: wasd_poller
    environment:
      API_TOKEN: ${TOKEN}
    depends_on:
      - app
      - db
    restart: always

  db:
    image: postgres:latest
    volumes:
      - ./wasd_data:/var/lib/postgresql/data
    container_name: wasd_db
    environment:
      POSTGRES_DB: wasd
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 6060:5432
    restart: always
