"""empty message

Revision ID: 537b4bd81fd9
Revises: 
Create Date: 2022-06-03 22:56:04.209053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537b4bd81fd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('subscriptions',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_name'], ['channels.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vk_id'], ['users.vk_id'], ),
    sa.PrimaryKeyConstraint('vk_id', 'channel_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('users')
    op.drop_table('channels')
    # ### end Alembic commands ###
